[2024-08-27 15:47:23] [INFO] [BaseApi.py]/[line: 70]/[get_token_by_file] 读取token文件失败或处理token时出错，错误信息为：HTTPConnectionPool(host='api.boweiedu.test', port=80): Max retries exceeded with url: /v1/user/login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F03D11F940>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')) 
[2024-08-27 15:49:53] [INFO] [BaseApi.py]/[line: 70]/[get_token_by_file] 读取token文件失败或处理token时出错，错误信息为：HTTPConnectionPool(host='api.boweiedu.test', port=80): Max retries exceeded with url: /v1/user/login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D59A3CB490>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')) 
[2024-08-27 19:40:37] [INFO] [BaseApi.py]/[line: 70]/[get_token_by_file] 读取token文件失败或处理token时出错，错误信息为：HTTPConnectionPool(host='api.boweiedu.test', port=80): Max retries exceeded with url: /v1/user/login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002931011F9D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')) 
[2024-08-27 19:41:18] [INFO] [BaseApi.py]/[line: 70]/[get_token_by_file] 读取token文件失败或处理token时出错，错误信息为：HTTPConnectionPool(host='api.boweiedu.test', port=80): Max retries exceeded with url: /v1/user/login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000228E532F1F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')) 
[2024-08-27 19:42:25] [INFO] [BaseApi.py]/[line: 70]/[get_token_by_file] 读取token文件失败或处理token时出错，错误信息为：HTTPConnectionPool(host='api.boweiedu.test', port=80): Max retries exceeded with url: /v1/user/login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000219876273D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')) 
